export default {
  "login": "tirthshah1999",
  "id": 64257672,
  "node_id": "MDQ6VXNlcjY0MjU3Njcy",
  "avatar_url": "https://avatars.githubusercontent.com/u/64257672?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/tirthshah1999",
  "html_url": "https://github.com/tirthshah1999",
  "followers_url": "https://api.github.com/users/tirthshah1999/followers",
  "following_url": "https://api.github.com/users/tirthshah1999/following{/other_user}",
  "gists_url": "https://api.github.com/users/tirthshah1999/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/tirthshah1999/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/tirthshah1999/subscriptions",
  "organizations_url": "https://api.github.com/users/tirthshah1999/orgs",
  "repos_url": "https://api.github.com/users/tirthshah1999/repos",
  "events_url": "https://api.github.com/users/tirthshah1999/events{/privacy}",
  "received_events_url": "https://api.github.com/users/tirthshah1999/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Tirth Shah",
  "company": "Asite Solutions",
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "Front End Web Developer ",
  "twitter_username": null,
  "public_repos": 41,
  "public_gists": 0,
  "followers": 150,
  "following": 100,
  "created_at": "2020-04-24T10:14:45Z",
  "updated_at": "2022-01-02T10:35:32Z"
};
